configMap:
  mountPath: /opt/gohello/params

server:
  port: 8080

  istio:
    injected: true

  readiness:
    path: /health_check

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi

worker:
  enabled: true

  command:
    - gohello
  args:
    - worker

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/limit-rps: "10"

  tls:
    - hosts:
        - gohello.zackijack.com

  hosts:
    - host: gohello.zackijack.com
      paths:
        - "/"

virtualService:
  enabled: true

  gateways:
    - backend/backend

  hosts:
    - api.machtwatch.net

  routes:
    - match:
        - uri:
            prefix: /gohello/
      retries:
        attempts: 3
        perTryTimeout: 2s
      rewrite:
        uri: /
      route:
        - destination:
            host: gohello
            port:
              number: 80
          weight: 100

autoscaling:
  minReplicas: 2
  maxReplicas: 20
